image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Build and Push to ECR
          services:
            - docker
          script:
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $ECR_REPOSITORY_NAME
                TAGS: '${BITBUCKET_COMMIT}'
      - step:
          name: Deploy to EC2
          script:
            - pipe: atlassian/aws-code-deploy:0.3.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $PROJECT_NAME-app
                DEPLOYMENT_GROUP: $PROJECT_NAME-deployment-group
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
            - pipe: atlassian/aws-code-deploy:0.3.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $PROJECT_NAME-app
                DEPLOYMENT_GROUP: $PROJECT_NAME-deployment-group
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'deploy'
                WAIT: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
