resource "tls_private_key" "dt_private" {
  # NOTE: This resource generates a 4096-bit RSA private key.  The private key is used for secure SSH access to the EC2 instance.
  # The public key is used to create the AWS key pair.
  algorithm = "RSA"
  rsa_bits  = 4096
}

# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair
resource "aws_key_pair" "dt_keypair" {
  # NOTE: This resource creates an AWS key pair using the public key generated by the 'tls_private_key' resource.
  # The key name is derived from the 'var.project_name' variable.  This key pair is used to allow SSH access to the EC2 instance.
  # It interacts with the 'instance.tf' file, which uses this key pair to launch the EC2 instance.
  key_name   = var.project_name
  public_key = tls_private_key.dt_private.public_key_openssh

  tags = {
    # NOTE: This block defines tags for the AWS key pair, primarily for organization and identification.
    Name = var.project_name
  }
}

# https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file
resource "local_file" "dt_rsa_private" {
  # NOTE: This resource creates a local file containing the private key generated by the 'tls_private_key' resource.
  # The filename is dynamically generated using the 'var.project_name' variable.
  # The file permissions are set to 0400 (read-only for the owner), ensuring the private key is protected.
  # This file is crucial for SSH access to the EC2 instance and should be kept secure.
  content         = tls_private_key.dt_private.private_key_pem
  filename        = "${path.module}/${var.project_name}.pem"
  file_permission = "0400"
}
