image: atlassian/default-image:3

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run test
        artifacts:
          - dist/**
          - node_modules/**

pipelines:
  default:
    - step: *build-test
  
  branches:
    main:
      - step: *build-test
      - step:
          name: Build and Push Docker Image
          services:
            - docker
          script:
            # - export IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY_NAME
            - export IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}"
            - export IMAGE_TAG=${BITBUCKET_COMMIT:0:7}
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                IMAGE_NAME: $IMAGE_NAME
                IMAGE_TAG: $IMAGE_TAG
  tags:
    v*:
      - step: *build-test
      - step:
          name: Build and Push Release Docker Image
          services:
            - docker
          script:
            # - export IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY_NAME
            - export IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}"
            - export IMAGE_TAG=${BITBUCKET_TAG}
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                IMAGE_NAME: $IMAGE_NAME
                IMAGE_TAG: $IMAGE_TAG